### ISSUE TITLE
The term 'dream' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by itchylol742** [lucidrains/big-sleep#14]
When I run the command I get an error. Using Powershell on Windows 10.

dream : The term 'dream' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ dream "a pyramid made of ice"
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (dream:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by enricoros** [comment]
How did you install this on Windows, using pip? virtualenv? maybe you need to specify the full path of the file. I'm using virtualenv on Windows, and running something like `C:\some\path\venv\Scripts\python.exe C:\some\path\modified-cli.py`

**Comment by itchylol742** [comment]
I ran it in the folder and it solved the problem
