### ISSUE TITLE
Question about Colab environments affecting results

### ISSUE THREAD

**Issue by stedn** [lucidrains/big-sleep#18]
This isn't really an issue, but I've been using this package to morph from one text input to the next by updating the input while its running and storing all intermediate output. I'm using variations of the notebook I've checked in here: https://github.com/lots-of-things/Story2Hallucination

When doing this I've gotten to really see inside how the algorithm converges on its solution.  And I've noticed that there are at least two distinct modes. Sometimes, the algorithm quickly converges and sticks and other times the algorithm wobbles around an image and then much more easily warps to something new.

Here's two images with the same input and framerate:
jerky/sticky
![output](https://user-images.githubusercontent.com/6944278/106078998-40653680-60c9-11eb-9b84-c7c934599951.gif)

wobbly/warpy
![output](https://user-images.githubusercontent.com/6944278/106079039-5541ca00-60c9-11eb-9bd3-df31d93af0f7.gif)

If these two modes happened randomly I'd understand it, but here is the really strange part.  This behavior will be consistent in the same colab environment.  If I pull up a colab env and run the notebook and it does the sticky way.  Then no matter how many times I restart the run, it will always be sticky.  I have to factory reset the env to get it to change.  Then if it starts to do it the wobbly way, it'll stay wobbly.

It sounds bizarre but is there any reason this would be possible? I know there are different CUDA environments, but not sure if/why that would make it so different.

**Comment by rynmurdock** [comment]
It could definitely be something in the BigSleep itself, but you may want to try seeing if CLIP's output varies wildly between Colab environments, as I've had issues like this as well -- and using a different PyTorch version seemed to fix it, but I don't know what's going on under the hood in CLIP.

**Comment by enricoros** [comment]
Have you checked the deterministic flag for CUDA operation and is this affecting your initial issue? I've seen the convergence/not convergence to be a function of the text. I.e. anything puppies converges very easily for me.

**Comment by glennamarshall** [comment]
In the Story2Hallucination notebook, it asks you to restart runtime after cuda install, then run all cells again - I found that this fixed the problem.

**Comment by stedn** [comment]
I haven't been able to trace it to anything specific. I've just accepted the process of restarting a few times until it looks good.
