### ISSUE TITLE
It's possible to use it in another languaje?

### ISSUE THREAD

**Issue by gamanox** [lucidrains/big-sleep#37]
what could be the way to make it work on another languaje? thanks a lot

**Comment by htoyryla** [comment]
I've seen a Colab of a similar project using Google translate to translate a prompt to English.

https://colab.research.google.com/drive/1rJMSyF_dmpL1kmse7Rm9TurjihJ_cA5t?fbclid=IwAR2KwCQXhL2u5OP_uhf46_9iqJofNbgW41h33pI2pRO_4caBiprtyKUTLfk#scrollTo=JUvpdy8BWGuM

I just quickly tried. First install googletrans:

`pip install googletrans==3.1.0a0`

and then in python:

```
from googletrans import Translator
translator = Translator()
translator.translate(text="maalaus vanhasta talosta puiden keskellä", src='fi', dest='en').text
```

which gives "'painting of an old house in the middle of trees'"

**Comment by gamanox** [comment]
thank you very much
