### ISSUE TITLE
ERROR: torchtext 0.9.0 has requirement torch==1.8.0, but you'll have torch 1.7.1+cu110 which is incompatible.

### ISSUE THREAD

**Issue by ipechman** [lucidrains/big-sleep#47]
I get this error when I try to run the first cell, and when I run big-sleep it gives me a white image as output.

**Comment by lucidrains** [comment]
@ipechman are you running the notebook or the CLI? and if the notebook, which one?

**Comment by ipechman** [comment]
I am running the simplified notebook

**Comment by lucidrains** [comment]
@ipechman Ok, I think its because colab upgraded to torch 1.8 recently, i've removed the first cell and it seems to work on my end!

**Comment by ipechman** [comment]
I will give it a try, I will tell you if it works

**Comment by ipechman** [comment]
It seems to be working for me too, I will update you when it finishes. Thank you for the help

**Comment by ipechman** [comment]
It's working now
