### ISSUE TITLE
Backslash character in file names.

### ISSUE THREAD

**Issue by pmonck** [lucidrains/big-sleep#72]
I'm now getting file names containing "\\" which were previously removed automatically. This is causing havoc when I attempt to use Windows to read files over the network which were created on my Linux system.

**Comment by lucidrains** [comment]
@pmonck I changed it to '|' instead https://github.com/lucidrains/big-sleep/commit/09671d2af212b08f3bf894add5d31db5af1dc28c

**Comment by lucidrains** [comment]
in 0.8.3, it'll change the | to a double dash too :)

**Comment by pmonck** [comment]
All working well now.
