### ISSUE TITLE
dream.set_text("a quiet pond underneath the midnight moon") = object has no attribute 'set_text'

### ISSUE THREAD

**Issue by nerdyrodent** [lucidrains/big-sleep#76]
Looks like def set_text is now def set_clip_encoding?
Also, various settings aren't honoured using dream.set_clip_encoding then dream (such as save_best = True). Would it be possible / make sense to retain settings from the previous dream?

**Comment by NotNANtoN** [comment]
Hi! True, it is renamed now and not updated in the README.

But what do you mean when you talk about retaining settings from a previous dream? Was this working before and now it does not work anymore? How does save_best influence all of this?

**Comment by nerdyrodent** [comment]
It's back :)

**Comment by nerdyrodent** [comment]
For "save_best", I was thinking for an example like below:

```
dream = Imagine(
    text = "An apple on fire",
    epochs = 6,
    append_seed = True,
    save_progress = False,
    save_best = True
)
dream()

dream.set_text("A pear on fire")
dream()
```
epochs, append seed and save_progress,etc all remain set when dreaming the pear, but save_best doesn't and so seems to be the "odd one out"?

**Comment by NotNANtoN** [comment]
Ah, I see. The issue is that `self.current_best_score` is not reset to 0 when `set_clip_encoding` is called, that only happens in the `__init__` at the moment. Maybe @lucidrains can quickly edit that?

**Comment by lucidrains** [comment]
@NotNANtoN fixed :)

**Comment by nerdyrodent** [comment]
Awesome! :)
