### ISSUE TITLE
Not Working with Nemo File Manager

### ISSUE THREAD

**Issue by tilktilk5** [lucidrains/big-sleep#88]
Installed successfully on Arch 5.11.16 with `pip install big-sleep` and it worked great but after a reboot it fails to generate images. After running any commands `prime-run dream --num-cutouts=25 --save-progress --save-every 100 "whatever"` or just `dream --num-cutouts 25 "whatever"` it opens the file manager (Nemo) to the directory but no images are generated. It sits while still using RAM but no GPU or CPU. Previously I was able to get it to work by reinstalling torch and big-sleep but that doesn't solve the problem anymore. 

Edit: After letting it sit for a few minutes, cancelling the command with CTRL+C shows `detecting keyboard interrupt, gracefully exiting` with empty progess bars before exiting.

Running with the `--open-folder False` option fixes this

**Comment by galaxyentity904** [comment]
I'm having a similar problem with Thunar file manager on Xubuntu. A fix would be appreciated

**Comment by galaxyentity904** [comment]
I have been experimenting because I needed to get this working.
Try lowering num_cutouts= to something like 64, but it may take longer
If that doesn't work try lowering image_size= to 128 or 256
